apiVersion: v1
kind: Pod
metadata:
  name: rust-server
  labels:
    app: rust-server
spec:
  containers:
  - name: rust-server
    image: esarawso2/rust_server
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
    - containerPort: 1234